SETTING_PARAMETER_NAME = "SETTING_PARAMETER_NAME"
SETTING_PARAMETER_STEP = "SETTING_PARAMETER_STEP"
SETTING_SHOW_PARAMETER_NAME = "SETTING_SHOW_PARAMETER_NAME"
SETTING_SHOW_PARAMETER_VALUE = "SETTING_SHOW_PARAMETER_VALUE"

SETTING_HOST = "SETTING_HOST"
SETTING_PORT = "SETTING_PORT"